### ISSUE TITLE
Reviewer Role: Show "History" link/module instead of Review Expenses Module

### ISSUE THREAD

**Issue by katjal** [tylercal/PTA-cash#1]
**Is your feature request related to a problem? Please describe.**
Our auditor used PTA Cash for the first time, and saw the "Review Expenses" module on the right side. She was very confused why the button was disabled, but was still visible. It did not occur to her to click on History to do the audit review. This might be due to the multiple meanings of the word "review".

**Describe the solution you'd like**
I think it would be clearest to have a "History" module appear for Reviewers/Auditors instead of the standard "Requests (Review Expenses)" module that appear for signers.

**Describe alternatives you've considered**
An alternative would be to have the Review Expenses button for "Reviewers" go to "History", but that could be confusing if there are two different behaviors for what appears to be the same thing.

**Additional context**
![PTA_Cash_Auditor_View](https://github.com/tylercal/PTA-cash/assets/1044923/6685ae55-1cc5-441c-a83c-0f0abfe2db58)

Please see screenshot

**Comment by tylercal** [comment]
yes, great suggestion. Any non-signer will now get a slightly different box (the button was never disabled, but it did do nothing if you tried to click it). Now it will actually take the user to the history view removing any open expense requests.

![image](https://github.com/tylercal/PTA-cash/assets/1126430/e3ae9a8d-5b87-470e-a816-b4e8b0f7b8a6)
